### DISCUSSION TITLE
How to set up CI build with license feed

### DISCUSSION THREAD

**Discussion by pmoleri** [IgniteUI/igniteui-blazor#136] [Q&A] [answered]
Hi,

What's the recommended way to set up CI build using Ignite licensed feed?

Here [blazor - general-nuget-feed](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/general-nuget-feed) it instructs to provide user and password.

If instead I try to get an API key from here:
![image](https://github.com/user-attachments/assets/b4e2f314-84d7-4219-8623-bbe9a8a30cb8)
https://account.infragistics.com/package-feeds

and then I use:
```cmd
nuget sources add -name "Infragistics" -source "https://packages.infragistics.com/nuget/licensed" -username "pmoler@..." -password "api:4e...."
```

but I get this error when installing/restoring Ignite package:
```
GET https://packages.infragistics.com/nuget/licensed/FindPackagesById()?id='IgniteUI.Blazor'&semVerLevel=2.0.0
info :   Forbidden https://packages.infragistics.com/nuget/licensed/FindPackagesById()?id='IgniteUI.Blazor'&semVerLevel=2.0.0 863ms
error: NU1301: Failed to retrieve information about 'IgniteUI.Blazor' from remote source 'https://packages.infragistics.com/nuget/licensed/FindPackagesById()?id='IgniteUI.Blazor'&semVerLevel=2.0.0'.
log  : Response status code does not indicate success: 403 (Forbidden)
```

**Comment by damyanpetev** [comment, marked as answer]
The usage was quite close, but indeed not the intended one and the documentation can use updates to explain better how to use the token.

Background: Outside of using a specific credential provider, NuGet doesn't really have a concept of authentication tokens (not to be confused with API keys which are for publish only). In fact, the docs for [Consuming packages from authenticated feeds](https://learn.microsoft.com/en-us/nuget/consume-packages/consuming-packages-authenticated-feeds) mention at the start it's quite typical to use token as NuGet's password and you have figured out as much.
The Basic authentication-style (ID and password joined by a single colon `:`) however is not really immediately obvious. So in essence, what you have is user name `api` paired with token `4e...` and that's true for the Infragistics license feed in general - it's always a static `api` username combined with your token as password.

That translates to the following in your case:
```cmd
nuget sources add -name "Infragistics" -source "https://packages.infragistics.com/nuget/licensed/" -username "api" -password "4e...."
```

Can also suggest a working snippet for GitHub Actions:
```yaml
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Authenticate
      run: dotnet nuget add source https://packages.infragistics.com/nuget/licensed/ -n Infragistics -u api -p "${NUGET_AUTH_TOKEN}" --store-password-in-clear-text
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
```
That's assuming the password portion of the token is stored in GitHub Actions secrets and you've already applied the token as secret (that's no longer editable) you can easily trim the static username like so `${NUGET_AUTH_TOKEN#api:}`.

I believe Azure DevOps Pipelines actually also had some neater provider integration that can be utilized, but like I said need to flesh out the docs more.
